"use client";
import { useRef, useState, useEffect } from "react";
import Image, { type ImageLoaderProps } from "next/image";
import { assetUrl } from "@/lib/assetUrl";

function heroImageLoader({ width }: ImageLoaderProps) {
 const size=width<=640?640:width<=960?960:1159;
 return assetUrl(`/timothy-illustration-${size}.webp`);
}
import { Copy, Check, Plus, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import MotionSystem from "./motion";
import CampaignThinking from "./campaign";

const email = "Timmotim66@gmail.com";
const whatsappHref = "https://wa.me/60182982325";
const lenses = [
  { id: "ads", label: "01. Start with the question", title: "A good ad starts with a good question.", copy: "Who are we trying to reach, and what would make them care? I turn those questions into keywords, ad copy and things worth testing", tools: ["Google Search Ads", "Meta Ads", "Keyword research", "Creative testing"], board: "Make it click.", notes: [["START HERE", "The right\naudience"], ["GIVE THEM", "A reason to care"], ["THEN", "Test, Learn"]], foot: "A little less guessing." },
  { id: "data", label: "02. See what the data says", title: "The click is only the beginning.", copy: "I track what happens after the click with GTM and GA4, then use CPC, CTR, CPL and conversion rate to spot what needs attention", tools: ["GTM", "GA4", "Conversion tracking", "Campaign analysis"], board: "Make it clear.", notes: [["01 / SOURCE", "Ad click"], ["02 / JOURNEY", "Website visit"], ["03 / OUTCOME", "Lead submitted"]], foot: "Every step should add up." },
  { id: "build", label: "03. Make the next move", title: "Curiosity is better when you build with it.", copy: "I use AI to research, analyse, build and troubleshoot. It helps me move faster, test ideas and turn rough thoughts into things people can actually use", tools: ["ChatGPT & Claude", "Cursor & Codex", "Canva & CapCut", "Product thinking"], board: "Make it real.", notes: [["THE QUESTION", "What if we tried…"], ["THE EXPERIMENT", "A working prototype"], ["THE NEXT STEP", "Listen,\nImprove"]], foot: "Then do it again." },
];
function Word({ children }: { children: string }) { return <span className="word" aria-label={children}>{[...children].map((c,i)=><span className="letter" aria-hidden="true" key={i}>{c===" "?"\u00a0":c}</span>)}</span>; }
function Board({ lens }: { lens: string }) { const l=lenses.find(l=>l.id===lens)!; return <div className={`thinking-board board-${lens}`}><div className="board-top"><span>ON MY DESK</span><span>0{lenses.indexOf(l)+1} / 03</span></div><div className="board-word">{l.board}</div><div className="board-path" aria-hidden="true"><svg viewBox="0 0 440 200" fill="none"><path className="dashed-path" d="M30 135C80 10 190 10 220 100S360 220 410 65" stroke="currentColor" strokeWidth="2" strokeDasharray="6 8"/></svg></div><div className="board-notes" key={lens}>{l.notes.map((n,i)=><div className={`board-note note-${i}`} key={n[0]}><small>{n[0]}</small><strong>{n[1]}</strong></div>)}</div><p className="board-hand">{l.foot}</p></div>; }

export default function Home(){
 const [lens,setLens]=useState("ads"),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 async function copyEmail(){
  let ok=false;
  try{await navigator.clipboard.writeText(email);ok=true;}catch{
   const active=document.activeElement as HTMLElement|null;
   const field=document.createElement("textarea");field.value=email;field.setAttribute("readonly","");field.style.cssText="position:fixed;left:-9999px";document.body.appendChild(field);field.select();
   try{ok=document.execCommand("copy");}catch{ok=false;}finally{field.remove();active?.focus();}
  }
  setCopyError(!ok);if(ok){setCopied(true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setCopied(false),2500);}
 }
 return <div className="portfolio" id="site"><a className="skip-link" href="#main">Skip to content</a>
 <header className="site-header"><a className="wordmark" href="#top" aria-label="Timothy, back to top">Timothy</a><nav aria-label="Main navigation"><a href="#skills">My approach</a><a href="#experience">Experience</a><a href="#campaign-thinking">Campaign thinking</a></nav><a className="nav-contact" href="#contact"><span className="nav-contact-label">Say hello <svg className="nav-inline-arrow" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg></span><svg className="nav-contact-doodle" viewBox="0 0 210 82" aria-hidden="true" focusable="false"><path className="doodle-fill" d="M18 34C44 16 112 9 145 21C168 29 168 47 143 56C112 66 66 68 30 69C7 69 3 52 18 34Z"/><path className="doodle-loop" d="M20 29C44 17 108 9 141 19C167 27 170 42 151 52C124 66 65 69 27 69C1 69 8 50 21 38"/><path className="doodle-echo" d="M12 23Q25 13 42 12M20 64C55 72 120 65 146 55"/><path className="doodle-tail" d="M97 77C135 78 170 65 185 46M174 48L186 44L181 57"/><path className="doodle-star" d="m195 10 2 7 7 1-6 4 1 7-5-5-7 3 3-7-4-5 7 1z"/></svg></a></header>
 <main id="main"><section className="hero" id="top" aria-labelledby="hero-title"><div className="hero-eyebrow"><span>PERFORMANCE MARKETING</span><span>KUALA LUMPUR, MY</span></div><div className="hero-layout"><div className="hero-copy"><h1 id="hero-title"><Word>This Is An Ad</Word><br/><Word>About</Word>{" "}<span className="human-word"><Word>Me</Word></span></h1><div className="hero-intro"><p>Hi, I’m Timothy<br/>I turn data into insights, ideas into action and both into smarter marketing</p><a className="ink-link" href="#skills">A little more me <span className="ink-link-arrow" aria-hidden="true">→</span></a></div></div><div className="hero-visual"><div className="hero-sticker"><div className="hero-sticker-inner"><span>ALWAYS<br/>A WORK<br/>IN PROGRESS</span></div></div><div className="hero-character"><Image className="hero-character-inner" src={assetUrl("/timothy-illustration.webp")} loader={heroImageLoader} unoptimized={false} sizes="(max-width: 760px) 311px, 480px" alt="Illustrated Timothy smiling and waving with a laptop" width={1159} height={1357} priority fetchPriority="high"/></div><span className="hero-tag">Yep, that’s me!</span><span className="hero-caption"><span>Ideas in my head.</span> <span>A few tabs open.</span></span></div></div><div className="hero-bottom"><span>KEEP GOING. I’M NOT DONE YET ↓</span><span className="scroll-track" aria-hidden="true"><i/></span><span>IDEAS ARE NICE. TESTED IDEAS ARE BETTER.</span></div></section>
  <section className="skills-section section-pad" id="skills" aria-labelledby="skills-title"><div className="section-index">01 / THE WAY I THINK</div><div className="skills-layout"><div className="skills-copy"><h2 id="skills-title" className="section-heading skills-heading"><Word>I like good ideas</Word><br/><Word>I like knowing</Word>{" "}<br className="skills-mobile-break"/><Word>why they work</Word></h2><p className="section-lede">That usually means asking questions, looking at the data and testing what comes next</p><Tabs value={lens} onValueChange={setLens} className="lens-tabs"><TabsList className="lens-list" aria-label="Explore my approach">{lenses.map(l=><TabsTrigger className="lens-trigger" value={l.id} key={l.id}>{l.label}<Plus aria-hidden="true"/></TabsTrigger>)}</TabsList>{lenses.map(l=><TabsContent value={l.id} key={l.id} className="lens-copy"><h3>{l.title}</h3><p>{l.copy}</p><div className="tool-list">{l.tools.map(t=><span key={t}>{t}</span>)}</div></TabsContent>)}</Tabs></div><Board lens={lens}/></div></section>
 <section className="experience-section section-pad" id="experience" aria-labelledby="experience-title"><div className="section-index">02 / SOME REAL-WORLD PRACTICE</div><div className="experience-heading"><h2 id="experience-title" className="section-heading">Less guesswork.<br/>More groundwork.</h2><p>Campaigns to run. Tracking to check.<br/>Always something to figure out</p></div><div className="stats-strip"><div><strong className="stat-number">30+</strong><span>active Google Search campaigns managed</span></div><div><strong className="stat-number">RM 10K</strong><span>peak livestream revenue in 6 hours,<br/>supported as an intern</span></div></div><Accordion type="single" collapsible defaultValue="cdd" className="experience-list"><AccordionItem value="cdd" className="experience-row"><AccordionTrigger className="experience-trigger"><span className="role-date">MAY 2025 — PRESENT</span><span><strong>Junior Campaign Specialist</strong><small>CDD Tech Sdn. Bhd.</small></span></AccordionTrigger><AccordionContent className="experience-detail"><p><strong>I keep campaigns moving, watch for changes, and figure out what needs attention next.</strong></p><ul><li>Check <strong>spend, CPL, impressions and CTR</strong> for unusual movement.</li><li>Review <strong>keywords and search terms</strong>, then adjust bids, add negatives or test new opportunities.</li><li>Set up and troubleshoot <strong>GTM and GA4</strong> tracking.</li><li>Test <strong>ad copy, keywords, ad groups, campaign objectives and creatives</strong>.</li><li>Work across <strong>Google Ads, Meta Ads and TikTok Ads</strong>, from setup to monitoring and troubleshooting.</li><li>Share daily updates and recommend <strong>next actions</strong> when something needs attention.</li></ul></AccordionContent></AccordionItem><AccordionItem value="moomooda" className="experience-row"><AccordionTrigger className="experience-trigger"><span className="role-date">OCT 2024 — JAN 2025</span><span><strong>Marketing Intern</strong><small>Moomooda Media Sdn Bhd</small></span></AccordionTrigger><AccordionContent className="experience-detail"><p>A hands-on introduction to the connection between content, engagement and sales.</p><ul><li>Monitored and optimized livestream performance.</li><li>Supported a livestream achieving peak revenue of RM 10K in 6 hours.</li><li>Analyzed engagement and sales data; supported short-form content through trend and competitor research.</li></ul></AccordionContent></AccordionItem></Accordion></section>
 <CampaignThinking/>
 <section className="about-section section-pad" id="about" aria-labelledby="about-title"><div className="section-index">04 / OFF THE SPREADSHEET</div><div className="about-layout"><div className="about-copy"><h2 id="about-title" className="section-heading">Curious by nature<br/>Learn by doing</h2><p>Marketing is my background. Kongsi is where I get to test ideas, improve the experience and learn by making</p></div><div className="about-photo"><div className="portrait-crop"><Image unoptimized src={assetUrl("/timothy-in-real-life.webp")} alt="Timothy smiling outdoors by the water" loading="lazy" width={1536} height={1148}/></div><span className="photo-caption">Timothy, in real life.</span></div><div className="about-facts"><div><small>EDUCATION</small><strong>Bachelor of Business (Hons) in Marketing</strong><span>TAR UMT · 2022–2025 · Dean’s List</span></div><div><small>LANGUAGES</small><strong>Chinese · English · Malay</strong><span>Native · Fluent · Intermediate</span></div></div></div></section>
 <section className="contact-section section-pad" id="contact" aria-labelledby="contact-title"><div className="section-index">05 / LET'S CONNECT</div><p className="contact-hand">Think I could be a good fit?</p><h2 id="contact-title" className="contact-title"><Word>Let’s talk.</Word></h2><div className="contact-row"><div className="contact-email"><a className="email-link" href={`mailto:${email}`}>{email}</a><Button className="copy-button" variant="ghost" onClick={copyEmail} aria-label="Copy email address">{copied?<Check size={20}/>:<Copy size={20}/>}</Button></div><a className="whatsapp-link" href={whatsappHref} target="_blank" rel="noopener noreferrer"><MessageCircle size={21} aria-hidden="true"/><span>Message me on WhatsApp</span></a></div><p className="copy-status" role="status">{copied?"Email copied. Say hello when you’re ready.":copyError?"Please select the email address to copy it.":""}</p><footer><span>© 2026 Timothy Yap Wei Zhong</span><a href="#top">Back to top</a></footer></section></main><MotionSystem/></div>;
}
